config/routes.rb
Rails.application.routes.draw do
  get "invitations/new"
  resources :organizations do
    resources :properties do
      resources :invitations, only: [:new, :create]
    end
    resources :members
    resources :invitations, only: [:new, :create]
  end
  get "dashboard" => 'dashboard#home'
  controller :sessions do
    get "login" => :new
    post "login" => :create
    get "logout" => :destroy
  end
  
  resources :users
  get "signup" => "users#new"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  get "/invitations/accept", to: "invitations#accept", as: :accept_invitation
end

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :organization
  has_many :invitations, as: :invitable
  has_many :tenants
  has_many :users, through: :tenants
  def address
    [
      address_line_one,
      address_line_two,
      city,
      state,
      postcode
    ].reject(&:blank?).join(', ')
end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_organization
  def index
  end

  def new
    @property = Property.new
  end

  def create
    @property = Property.new(property_params)
    @property.organization = @organization
    if @property.save
      redirect_to [@organization, @property]
    else
      render :new
    end
  end


  def edit
  end

  def show
    @property = Property.find(params[:id])
  end

  private

  def set_organization
    @organization = Organization.find(params[:organization_id])
  end

  def property_params
    params.expect(property: [:address_line_one, :address_line_two, :postcode, :city, :state])
  end
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/properties/edit.html.erb
<h1>Properties#edit</h1>
<p>Find me in app/views/properties/edit.html.erb</p>

app/views/properties/index.html.erb
<h1>Properties#index</h1>
<p>Find me in app/views/properties/index.html.erb</p>

app/views/properties/new.html.erb
<h1>Properties#new</h1>
<p>Find me in app/views/properties/new.html.erb</p>
<%= form_with(model: [@organization, @property]) do |form| %>
    <%= form.label :address_line_one %>
    <%= form.text_field :address_line_one %>
    <%= form.label :address_line_two %>
    <%= form.text_field :address_line_two %>
    <%= form.label :postcode %>
    <%= form.text_field :postcode %>
    <%= form.label :city %>
    <%= form.text_field :city %>
    <%= form.label :state %>
    <%= form.text_field :state %>
    <%= form.submit "Add property" %>
<% end %>

app/views/properties/show.html.erb
<h1>Properties#show</h1>
<p>Find me in app/views/properties/show.html.erb</p>
<%= @property.address %>
<%= link_to "Add a tenant to this property", new_organization_property_invitation_path(@organization, @property) %>